### EMPLEADOS ###

GET http://localhost:3000/api/empleados

###

POST http://localhost:3000/api/empleados
Content-Type: application/json

{
    "nombre": "Geremías",
    "dni": "15526789-E",
    "sexo": "M",
    "fecha_nac": "1986-09-09",
    "salario": 1500,
    "cargo": "coordinador"
}

###

PUT http://localhost:3000/api/empleados
Content-Type: application/json

{
    "id": 25,
    "nombre": "Juanita",
    "dni": "03807090-Z",
    "sexo": "F",
    "fecha_nac": "1983-05-23",
    "salario": 4200,
    "cargo": "ayudante de dirección"
}

###

DELETE http://localhost:3000/api/empleados
Content-Type: application/json

{
    "id": 28
}

### DEPARTAMENTOS ###

GET http://localhost:3000/api/departamentos

###
POST http://localhost:3000/api/departamentos
Content-Type: application/json

{
    "nombre": "aviación",
    "ciudad": "Toledo"
}

###
PUT http://localhost:3000/api/departamentos
Content-Type: application/json

{
    "nombre": "robótica",
    "ciudad": "Valencia",
    "id": 9
}

###
DELETE http://localhost:3000/api/departamentos
Content-Type: application/json

{
    "id": 10
}
